# Site settings
title: Nerd in the wild.
description: >-  # this means to ignore newlines until "baseurl:"
 <H1> Please excuse the mess you find here</H1>
 Trying a bunch of things here.
 
 <p>An old nerds journey in finding Employment and the evil that is badly written code.
 Lets See if this internet thing works (still think stone tablets where cool).
 <br>
  <p>Always code as if the guy who ends up maintaining your code
  will be a violent psychopath who knows where you live.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: github.com/bjamey
#remote_theme: YoussefRaafatNasry/portfolYOU



# Build settings
markdown: kramdown
# plugins_dir:
# - jekyll-feed


# Author Info
author:
  name     : Ben Amey
  image    : assets/img/digital-brain-cirquit.jpg
  email    : bjamey@gmail.com
  github   : bjamey
  twitter  : icoffeemonkey
  linkedin : ben-amey-82a44070
  facebook : 


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name:output_ext


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: /articles/:title:output_ext


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE

